In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sbn

# ilk konumuz eksik verlileri basit bir şekilde doldurmak


In [2]:
veri=pd.read_csv("eksikveriler.csv")
boy=veri["boy"]
kilo=veri["kilo"]
yas=veri["yas"]
ulke=veri["ulke"]
cins=veri["cinsiyet"]
boykilo=[["boy"],["kilo"]]

* simpleimputer bu işte baya işimize yarayacak bir kütüphanedir

In [3]:
from sklearn.impute import SimpleImputer

*missing_values ile hedef alınan kısmı seçiyoruz sonrada nasıl yapacağımıza strateji ile karar veriyoruz

In [4]:
imputer=SimpleImputer(missing_values=np.nan,strategy="mean")

*ilk olarad 1 ve 4. kolonlar arasındaki sayısal verileri alalım

In [5]:
Yas=veri.iloc[:,1:4].values

*sonra bu Yas verisini bilgisayarın öğrenmesi için imputere fit ettirticez

In [6]:
imputer=imputer.fit(Yas[:,1:4])

*daha sonra imputere transform ettirterek öğrendiklerini uygulattırtıcaz

In [7]:
Yas[:,1:4]=imputer.transform(Yas[:,1:4])
print(Yas)

[[130.    30.    10.  ]
 [125.    36.    11.  ]
 [135.    34.    10.  ]
 [133.    30.     9.  ]
 [129.    38.    12.  ]
 [180.    90.    30.  ]
 [190.    80.    25.  ]
 [175.    90.    35.  ]
 [177.    60.    22.  ]
 [185.   105.    33.  ]
 [165.    55.    27.  ]
 [155.    50.    44.  ]
 [160.    58.    28.45]
 [162.    59.    41.  ]
 [167.    62.    55.  ]
 [174.    70.    47.  ]
 [193.    90.    28.45]
 [187.    80.    27.  ]
 [183.    88.    28.  ]
 [159.    40.    29.  ]
 [164.    66.    32.  ]
 [166.    56.    42.  ]]


## 2 SEÇENEKLİ VERİLERİ MAKİNENİN ANLAYACAĞI ŞEKLE ,0 VE 1 HALİNDE KATEGORİZE ETMEK

In [8]:
ulke=veri.iloc[:,0:1].values
from sklearn import preprocessing
le=preprocessing.LabelEncoder()
ulke[:,0]=le.fit_transform(veri.iloc[:,0])


*labelencoder verileri sayıya çevirir ilk denk gelene 1 ikincisine 2 3. denk gelene 2 son denk gelen ifadeye de 0 verir

In [9]:
print(ulke)


[[1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]]


*onehotencodder ise her değeri yeni birer kolon haline getirerek eğer fransızsa fr ye 1 geri kalana 0 verdirttirir

*bu yöntemler bize kategorik verileri sayısal veriye dönüştürmeyi sağlarlar dolayısı ile ilerki aşamada çok işimize yararlar

In [10]:
ohe=preprocessing.OneHotEncoder()
ulke=ohe.fit_transform(ulke).toarray()
print(ulke)

[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]


VERİLERİ BİRLEŞTİRMEK

In [11]:
sonuc=pd.DataFrame(columns=["fr","tr","usa"],data=ulke)
print(sonuc)

     fr   tr  usa
0   0.0  1.0  0.0
1   0.0  1.0  0.0
2   0.0  1.0  0.0
3   0.0  1.0  0.0
4   0.0  1.0  0.0
5   0.0  1.0  0.0
6   0.0  1.0  0.0
7   0.0  1.0  0.0
8   0.0  1.0  0.0
9   0.0  0.0  1.0
10  0.0  0.0  1.0
11  0.0  0.0  1.0
12  0.0  0.0  1.0
13  0.0  0.0  1.0
14  0.0  0.0  1.0
15  1.0  0.0  0.0
16  1.0  0.0  0.0
17  1.0  0.0  0.0
18  1.0  0.0  0.0
19  1.0  0.0  0.0
20  1.0  0.0  0.0
21  1.0  0.0  0.0


In [12]:
sonuc2=pd.DataFrame(data=Yas,columns=["boy","kilo","yas"])
sonuc3=pd.DataFrame(data=cins,columns=["cinsiyet"])
sons=pd.concat([sonuc,sonuc2],axis=1)
sonsonuc=pd.concat([sons,sonuc3],axis=1)
print(sonsonuc)

     fr   tr  usa    boy   kilo    yas cinsiyet
0   0.0  1.0  0.0  130.0   30.0  10.00        e
1   0.0  1.0  0.0  125.0   36.0  11.00        e
2   0.0  1.0  0.0  135.0   34.0  10.00        k
3   0.0  1.0  0.0  133.0   30.0   9.00        k
4   0.0  1.0  0.0  129.0   38.0  12.00        e
5   0.0  1.0  0.0  180.0   90.0  30.00        e
6   0.0  1.0  0.0  190.0   80.0  25.00        e
7   0.0  1.0  0.0  175.0   90.0  35.00        e
8   0.0  1.0  0.0  177.0   60.0  22.00        k
9   0.0  0.0  1.0  185.0  105.0  33.00        e
10  0.0  0.0  1.0  165.0   55.0  27.00        k
11  0.0  0.0  1.0  155.0   50.0  44.00        k
12  0.0  0.0  1.0  160.0   58.0  28.45        k
13  0.0  0.0  1.0  162.0   59.0  41.00        k
14  0.0  0.0  1.0  167.0   62.0  55.00        k
15  1.0  0.0  0.0  174.0   70.0  47.00        e
16  1.0  0.0  0.0  193.0   90.0  28.45        e
17  1.0  0.0  0.0  187.0   80.0  27.00        e
18  1.0  0.0  0.0  183.0   88.0  28.00        e
19  1.0  0.0  0.0  159.0   40.0  29.00  

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
x_train,x_test,ytrain,y_test=train_test_split(sons,sonuc3,test_size=0.30,random_state=0)